events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream frontend_board {
        server board:4182; # <-- On revient sur 4182 car l'image écoute ici
    }

    upstream backend_innkeeper {
        server innkeeper:4181;
    }

    server {
        listen 80;
        server_name localhost;

        # 1. Le Frontend React
        location / {
            proxy_pass http://frontend_board;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 2. Le Backend Node.js
        location /api/ {
            proxy_pass http://backend_innkeeper;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}